version: '2'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "34000:6000"
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web1
    ports:
      - "34001:6000"
  web2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web2
    ports:
      - "34002:6000"
  app:
    image: dockerapp:latest
    container_name: app
    ports:
      - "35000:6000"

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config:

